### ISSUE TITLE
Please add AES256 encryption

### ISSUE THREAD

**Issue by schich02** [aicodix/rattlegram#11]
It would be super cool to have an aes256 encryption feature. Please add optional encryption.

**Comment by xdsopl** [comment]
Sorry, won't happen. Encryption over amateur radio ain't legal in most countries.

**Comment by schich02** [comment]
Well, gotta do it my self then. Do you bother me cloning the app, implementing it myself and then publishing it?

**Comment by xdsopl** [comment]
I welcome it. Please do not get yourself or others who use the app with encryption into trouble. Have fun!

**Comment by ctrmass** [comment]
I'd be interested in this when it reaches fruition.
73
Eric
