### ISSUE TITLE
[Suggestion] Changeable delay time between RX and TX in Parrot mode

### ISSUE THREAD

**Issue by facmachado** [aicodix/rattlegram#15]
Hello,
I'm testing the parrot mode between two radios, but one of them repeats back too quickly, while the other is still in tx mode, preventing it from receiving.
An adjustable delay time would be a great option for parrot mode.
Thank you and 73.

**Comment by xdsopl** [comment]
Thank you for the excellent suggestion. I am also planing to add a mechanism to prevent an infinite ping-pong of the same message between repeaters. Try it, it's fun. ^_^
Meanwhile I can suggest you to add a longer "Leading Noise" time at the repeater, which will give you some delay.

**Comment by xdsopl** [comment]
Added with commit 0ad243688c7d801b9c0088770f4c052a1eb5db51

**Comment by xdsopl** [comment]
Added repeater debouncing with commit 4b664eb29cbdad6a6a8ad35b7140a28aa829b64f

**Comment by xdsopl** [comment]
The two changes are included in the v1.12 release on the beta channel of the Google Play Store for testing and should be distributed over next few days.
If you are impatient, you can download the APKs and test immediately:
https://github.com/aicodix/rattlegram/releases/tag/v1.12
