### ISSUE TITLE
Feature suggestion: Hard messaging time limits (Useful for GMRS integration)

### ISSUE THREAD

**Issue by kenbuckler** [aicodix/rattlegram#18]
Rattlegram could be extremely useful in helping remove barriers to entry for GMRS data transmissions. Data transmissions over GMRS are now permitted per FCC, but with strict requirements.

However, two settings need to be added in order to accomplish this. Both of these settings should be configurable, or disable as needed.

1) Maximum transmit time - Configurable in milliseconds, calculates the time needed to transmit the data and refuses transmit if time would exceed due to message length
2) Minimum time between messages - Configurable in milliseconds, calculates time since the last message was sent, and holds transmission if time would be less than the minimum value

https://www.ecfr.gov/current/title-47/chapter-I/subchapter-D/part-95/subpart-E
§ 95.1787 GMRS additional requirements.
Each hand-held portable unit transmitter type submitted for certification under this subpart is subject to the rules in this section. 
(a) Digital data transmissions.  GMRS hand-held portable units that have the capability to transmit digital data must be designed to meet the following requirements. 
...
(2) Digital data transmissions must not exceed one second in duration. 
(3) Digital data transmissions must not be sent more frequently than one digital data transmission within a thirty-second period, except that a GMRS unit may automatically respond to more than one interrogation request received within a thirty-second period.

**Comment by xdsopl** [comment]
Thank you for bringing this up but Rattlegram will stay as a SMS service only. This means that each transmit is only a second long and is controlled by a human operator. Our next file transmission app (in the works) will have the mentioned mechanisms in order to obey the rules, as automated file transmissions take much longer and work without human intervention.

**Comment by SHTFCOMM** [comment]
Not for nothing, but there is some thought that this sort of thing could fly in the face of the FCC as § 95.339 --> § 95.1787(A)(5)

At least for now, this all will most likely change based on the current waiver titled "Midland Radio Corporation Petition for Waiver of Certain FCC’s Rules to Authorize a Radio System to Improve Safety for Off-Road GMRS Users" (https://docs.fcc.gov/public/attachments/DA-23-633A1.pdf)

**Comment by ropucyka** [comment]
> Our next file transmission app (in the works)

Any news? 1 year. Data over Baofeng? Yaayy

**Comment by xdsopl** [comment]
We have other priorities at the moment
