### ISSUE TITLE
Request: GPS

### ISSUE THREAD

**Issue by rmacmorran** [aicodix/rattlegram#25]
Allow sending system-provided GPS coordinates with a button or setting.
Consider:
Menu setting to send coordinates at interval and/or setting to send when position changes by a minimum distance.
Automatically converting decoded coordinates to a link to launch in the system's configured mapping app.

**Comment by xdsopl** [comment]
Yes, that is a nice suggestion. I hope it won't spook off some users when we start to ask for GPS permissions. It needs to be off by default and clearly stated what we do with that information. As always, code contributions are welcome.

**Comment by rmacmorran** [comment]
I'd have to learn android development first, but I'll look into it.
An alternative, since you can already share links from any app including mapping apps, would be to detect messages that contain links and allow the hyperlink to be clicked and launched in the default app.

**Comment by xdsopl** [comment]
I'd be happy to help with this if needed. Detecting and making links clickable is a fantastic suggestion! To streamline implementation, consider creating a separate feature request focused solely on this functionality.

**Comment by maxbrito500** [comment]
> Yes, that is a nice suggestion. I hope it won't spook off some users when we start to ask for GPS permissions. It needs to be off by default and clearly stated what we do with that information. As always, code contributions are welcome.

This can be a definition on the settings and ask for permission when activated. I think it makes a lot of sense, especially to serve as automated beacon every NN minutes while on the move
