### ISSUE TITLE
Error After Build

### ISSUE THREAD

**Issue by mdwoicke** [aicodix/rattlegram#29]
I just wanted to say first that I was extremely impressed after trying this app on the Android Play Store that I had to try it out to see if I could possibly use it in a personal app I am working on. I came across your app here but having issues with it.

It shows it was able to build successfully but then throws the following error and I am unable to run it. I made sure it was not a naming issue in the config files. Any help is appreciated tremendously!

Error: java.lang.IllegalStateException: Module entity with name: rattlegram should be available

**Comment by mdwoicke** [comment]
Is this offered as a hosted API service on any platform by chance?

**Comment by cryptze** [comment]
I just cloned the repo, and build it on Android Studio in Linux Mint. The only issue I had is the need to install ninja build.

 sudo apt install ninja-build
