### ISSUE TITLE
Downloading an encoded message as an audio file

### ISSUE THREAD

**Issue by stefopl** [aicodix/rattlegram#3]
Would it be possible to have a button next to the message that would allow you to download the encoded message as an audio file, e.g. mp3

**Comment by xdsopl** [comment]
I am sure you meant encoded, as encryption will never be supported in Rattlegram.
If you need audio files, you maybe want to look at the command line version of the modem here:
https://github.com/aicodix/modem/tree/short

**Comment by stefopl** [comment]
Of course, I meant encoded.
This was a question forwarded from a group of users who have been using the app a lot lately.
Thanks for the link to the modem. They will pass it on, but it would probably be more convenient for them to do it in the application.

**Comment by stefopl** [comment]
I generated a``` test.wav``` file using a modem ```./encode test.wav 8000 16 1 test.dat```
When I play it Rattlegram says ```ANONYMOUS - Model 6 unsupported```
How to get it to work and how to add Call Sign

**Comment by xdsopl** [comment]
You need to checkout the ```short``` branch, that's the modem used in Rattlegram

**Comment by stefopl** [comment]
Thanks. It now decodes correctly. I made a small web interface for this. For now, it should be enough for my friends, but think about adding an option to download audio files in the application.

**Comment by xdsopl** [comment]
Cool, making a WASM web page out of Rattlegram is also on my TODO list. If you are interested, look at my examples:
https://www.aicodix.de/example3/
