### ISSUE TITLE
C4FM problem 

### ISSUE THREAD

**Issue by Doug-F** [aicodix/rattlegram#30]
Rattlegram doesn't work on Yaesu's C4FM, when it's fine on FM.  We use a repeater that doesn't handle FM, can anything be done to make it work?

**Comment by xdsopl** [comment]
Digital voice transmissions use vocoder technology combined with compression to improve human voice transmission clarity over noisy channels. On the other hand, Rattlegram uses OFDM technology to transmit a bandwidth limited signal, which does not resemble human speech but is okay with SSB, AM and FM. Transmitting data over a digital voice channel is a different kind of challenge.
