### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by lkhodel** [aicodix/rattlegram#6]
I'm unable to build this project on Windows 10 under Android Studio with the latest updates. 

The message I get is:
```
No variants found for ':app'. Check build files to ensure at least one variant exists. at:
com.android.tools.idea.gradle.project.sync.AndroidModule.prepare(GradleModules.kt:266)
```

Are there build instructions online or some alternative script?

**Comment by cryptze** [comment]
Same issue, will try with Mac and Ubuntu.
