### ISSUE TITLE
Reverse message list (newes down, oldest up like WhatsApp Signal etc.)

### ISSUE THREAD

**Issue by schnepe2** [aicodix/rattlegram#8]
The title says it all (i hope).
This is more of a "whish" from a userability point of view, as users usually are accustomed to this behaviour from other Apps.

**Comment by xdsopl** [comment]
Thank you for the suggestion. Yes, it would be nice to switch between both behaviors. Unfortunately the solution to always show the newest message on the bottom of the list is a bit awkward, both to implement and IMHO to use. If someone wants to implement it, please step forward, pull requests are very welcome. ;-)

**Comment by schnepe2** [comment]
Sure this behaviour should be configurable.
I have never build an Android App, so this might not be quick 😄 , but I'll see what I can do.
Possibly I'll start with a "much simpler" feature pull-request first (like the requested #4  issue).
Thanks for the response and don't expect things to soon 😉

**Comment by xdsopl** [comment]
Cool. I am here if you get stuck.
