### ISSUE TITLE
Potential for compound callsign support?

### ISSUE THREAD

**Issue by cjtheham** [aicodix/rattlegram#9]
I was out of my home country this week and experimenting with Rattlegram/Ribbit with some friends and discovered the / character is not supported at all for callsigns in app, and the character limit is even too small. This required me to have to ID in voice for my transmissions to stay within legal requirements instead of simply IDing through my data transmission.

Is the lack of / and the limit for 9 character callsigns a limit of just the app itself, or the protocol? Is there any hope for compound call support in the future?

**Comment by xdsopl** [comment]
The COFDMTV protocol used for Rattlegram has a fixed preamble format that can't be changed. The callsign is limited to nine alpha numeric characters and spaces, much like the international morse code. You could use a space character in place of a slash character instead. Ribbit won't have that limitation, as we use a different preamble and data format.
